[model]
path = "aircraft/aircraft.obj"
# path = "dragon/dragon.obj"
# path = "cyborg/cyborg.obj"
# path = "nanosuit/nanosuit.obj"
# path = "fireplace_room/fireplace_room.obj"

[camera]
# Aircraft
position = [-4.0, 2.8, 5.0]
forward = [1.0, -0.5, -1.0]

# Dragon
# position = [-1.0, 0.0, 0.0]
# forward = [1.0, 0.0, 0.0]

# Cyborg
# position = [0.0, 4.5, 5.0]
# forward = [0.0, -0.5, -1.0]

# Nanosuit
# position = [0.0, 18.0, 20.0]
# forward = [0.0, -0.5, -1.0]

# Fireplace
# position = [4.0, 2.0, -0.2]
# forward = [-1.0, -0.4, -1.0]

up = [0.0, 1.0, 0.0]
fovy = 45.0

[light]
position = [-4.0, 2.8, 7.0]

# Nanosuit
# position = [0.0, 20.0, 20.0]

# Fireplace
# position = [3.0, 2.87, -0.5]

[ray_recursion]
depth = 5

[shading_defaults]
shininess = 32
ambient = 0.1
diffuse = 0.4
specular = 0.4