[model]
path = "aircraft/aircraft.obj"
# path = "dragon/dragon.obj"
# path = "fireplace_room/fireplace_room.obj"
# path = "gun/gun.obj"

[camera]
# Aircraft
position = [-4.0, 2.8, 5.0]
forward = [1.0, -0.5, -1.0]

# Dragon
# position = [-1.0, 0.0, 0.0]
# forward = [1.0, 0.0, 0.0]

# Fireplace
# position = [4.0, 2.0, -0.2]
# forward = [-1.0, -0.4, -1.0]

# Gun
# position = [0.5, 0.2, -1.5]
# forward = [-0.75, -0.25, 1.0]

up = [0.0, 1.0, 0.0]
fovy = 45.0

[light]
position = [-4.0, 2.8, 7.0]
intensity = [500.0, 500.0, 500.0]

# Gun
# position = [3.0, 1.0, 4.5]

[ray_recursion]
depth = 5

[shading_defaults]
diffuse = [1.0, 1.0, 1.0]
metallic = 0.5
roughness = 0.1
ambient_occlusion = 1.0