[output]
dimensions = [1280, 720]
file_path = "nova.jpg"
num_samples = 1024

[post_processing]
anti_aliasing = false
exposure = 1.0

#---------------------------------------------------------------------------------------------------
# Aircraft
#---------------------------------------------------------------------------------------------------
# [model]
# paths = ["aircraft/aircraft.obj"]
# sky = "sky/lakeside_4k.hdr"

# [camera]
# position = [-1.9, 0.7, 1.6]
# target = [0.0, 0.0, 0.0]
# up = [0.0, 1.0, 0.0]
# fovy = 45.0

# [[light]]
# position = [-1.4, 2.0, 2.5]
# normal = [0.0, -1.0, 0.0]
# dims = [0.5, 0.5]
# intensity = [500.0, 500.0, 500.0]

# [shading_defaults]
# diffuse = [1.0, 1.0, 1.0]
# metallic = 0.8
# roughness = 0.5

# [ground]
# position = [0.0, -0.8, 0.0]
# normal = [0.0, 1.0, 0.0]
# dims = [5.0, 5.0]
# diffuse = [0.6, 0.6, 0.6]
# metallic = 0.01
# roughness = 0.01

#---------------------------------------------------------------------------------------------------
# Dragon
#---------------------------------------------------------------------------------------------------
# [model]
# paths = ["dragon/dragon.glb"]
# sky = "sky/lakeside_4k.hdr"

# [camera]
# position = [-1.7, 1.1, -0.8]
# target = [0.0, -0.1, 0.0]
# up = [0.0, 1.0, 0.0]
# fovy = 45.0

# [[light]]
# position = [-1.4, 1.7, -2.0]
# normal = [0.0, -1.0, 0.0]
# dims = [0.5, 0.5]
# intensity = [500.0, 500.0, 500.0]

# [shading_defaults]
# diffuse = [1.0, 1.0, 1.0]
# metallic = 0.4
# roughness = 0.1

# [ground]
# position = [0.0, -0.8, 0.0]
# normal = [0.0, 1.0, 0.0]
# dims = [5.0, 5.0]
# diffuse = [0.2, 0.2, 0.2]
# metallic = 0.01
# roughness = 0.01

#---------------------------------------------------------------------------------------------------
# Fireplace
#---------------------------------------------------------------------------------------------------
[model]
paths = ["fireplace_room/fireplace_room.glb"]
sky = "sky/lakeside_4k.hdr"

[camera]
position = [1.0, 0.3, -0.4]
target = [0.0, 0.0, 0.0]
up = [0.0, 1.0, 0.0]
fovy = 45.0

[[light]]
position = [0.8, 0.5, -0.6]
normal = [0.0, -1.0, 0.0]
dims = [0.2, 0.2]
intensity = [50.0, 50.0, 50.0]

[shading_defaults]
diffuse = [1.0, 1.0, 1.0]
metallic = 0.5
roughness = 0.1

#---------------------------------------------------------------------------------------------------
# Gun
#---------------------------------------------------------------------------------------------------
# [model]
# paths = ["gun/gun.glb"]
# sky = "sky/lakeside_4k.hdr"

# [camera]
# position = [0.6, 0.35, -1.3]
# target = [-0.4, 0.0, -0.1]
# up = [0.0, 1.0, 0.0]
# fovy = 45.0

# [[light]]
# position = [1.6, 0.5, 2.5]
# normal = [0.0, -1.0, 0.0]
# dims = [1.0, 1.0]
# intensity = [500.0, 500.0, 500.0]

# [shading_defaults]
# diffuse = [1.0, 1.0, 1.0]
# metallic = 0.5
# roughness = 0.1

#---------------------------------------------------------------------------------------------------
# Cornell Box
#---------------------------------------------------------------------------------------------------
# [model]
# paths = ["cornell_box/CornellBox-Original.obj"]
# sky = "sky/lakeside_4k.hdr"

# [camera]
# position = [0.0, 0.0, 5.0]
# target = [0.0, 0.0, 0.0]
# up = [0.0, 1.0, 0.0]
# fovy = 30.0

# [shading_defaults]
# diffuse = [1.0, 1.0, 1.0]
# metallic = 0.5
# roughness = 0.1
