[output]
dimensions = [1280, 720]
file_path = "nova.jpg"

[other]
num_samples = 1024
ray_bounces = 5
exposure = 1.0

[post_processing]
anti_aliasing = false

#---------------------------------------------------------------------------------------------------
# Aircraft
#---------------------------------------------------------------------------------------------------
[model]
paths = ["aircraft/aircraft.obj"]
sky = "sky/lakeside_4k.hdr"

[camera]
position = [-1.9, 0.7, 1.6]
target = [0.0, 0.0, 0.0]
up = [0.0, 1.0, 0.0]
fovy = 45.0

[light]
position = [-4.0, 2.8, 7.0]
normal = [0.0, -1.0, 0.0]
size = 0.2
intensity = [500.0, 500.0, 500.0]

[shading_defaults]
diffuse = [1.0, 1.0, 1.0]
metallic = 0.8
roughness = 0.5
ambient_occlusion = 1.0

#---------------------------------------------------------------------------------------------------
# Dragon
#---------------------------------------------------------------------------------------------------
# [model]
# paths = ["dragon/dragon.glb"]
# sky = "sky/lakeside_4k.hdr"

# [camera]
# position = [-1.7, 1.1, -0.8]
# target = [0.0, 0.0, 0.0]
# up = [0.0, 1.0, 0.0]
# fovy = 45.0

# [light]
# position = [-4.0, 5.0, -6.0]
# normal = [0.0, -1.0, 0.0]
# size = 0.2
# intensity = [500.0, 500.0, 500.0]

# [shading_defaults]
# diffuse = [1.0, 1.0, 1.0]
# metallic = 0.8
# roughness = 0.1
# ambient_occlusion = 1.0

#---------------------------------------------------------------------------------------------------
# Fireplace
#---------------------------------------------------------------------------------------------------
# [model]
# paths = ["fireplace_room/fireplace_room.glb"]
# sky = "sky/lakeside_4k.hdr"

# [camera]
# position = [1.0, 0.3, -0.4]
# target = [0.0, 0.0, 0.0]
# up = [0.0, 1.0, 0.0]
# fovy = 45.0

# [light]
# position = [0.8, 0.4, -0.6]
# normal = [0.0, -1.0, 0.0]
# size = 0.2
# intensity = [5.0, 5.0, 5.0]

# [shading_defaults]
# diffuse = [1.0, 1.0, 1.0]
# metallic = 0.5
# roughness = 0.1
# ambient_occlusion = 1.0

#---------------------------------------------------------------------------------------------------
# Gun
#---------------------------------------------------------------------------------------------------
# [model]
# paths = ["gun/gun.glb"]
# sky = "sky/lakeside_4k.hdr"

# [camera]
# position = [0.6, 0.35, -1.3]
# target = [-0.4, 0.0, -0.1]
# up = [0.0, 1.0, 0.0]
# fovy = 45.0

# [light]
# position = [3.0, 1.0, 4.5]
# normal = [0.0, -1.0, 0.0]
# size = 0.2
# intensity = [500.0, 500.0, 500.0]

# [shading_defaults]
# diffuse = [1.0, 1.0, 1.0]
# metallic = 0.5
# roughness = 0.1
# ambient_occlusion = 1.0

#---------------------------------------------------------------------------------------------------
# Cornell Box
#---------------------------------------------------------------------------------------------------
# [model]
# paths = ["cornell_box/CornellBox-Original.obj"]
# sky = "sky/lakeside_4k.hdr"

# [camera]
# position = [0.0, 0.0, 5.0]
# target = [0.0, 0.0, 0.0]
# up = [0.0, 1.0, 0.0]
# fovy = 30.0

# [light]
# position = [0.8, 0.4, -0.6]
# normal = [0.0, -1.0, 0.0]
# size = 0.2
# intensity = [5.0, 5.0, 5.0]

# [shading_defaults]
# diffuse = [1.0, 1.0, 1.0]
# metallic = 0.5
# roughness = 0.1
# ambient_occlusion = 1.0
